USE CAR_HISTORY;
CREATE TABLE CARS
(
    ID INT NOT NULL IDENTITY,
    CAR_NAME VARCHAR(50) NOT NULL,
    CAR_BRAND VARCHAR(50) NOT NULL,
    CAR_MODEL VARCHAR(50) NOT NULL,
    CAR_YEAR INT NOT NULL,
    CAR_PLATE VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID)
);
CREATE TABLE EVENTS
(
    ID INT NOT NULL IDENTITY,
    CAR_ID INT NOT NULL,
    EVENT_DATE DATE NOT NULL,
    EVENT_MILLAGE INT NOT NULL,
    EVENT_DESCRITION VARCHAR(50) NOT NULL,
    EVENT_REPEATABLE BIT NOT NULL,
    NEXT_EVENT_DATE DATE NOT NULL,
    NEXT_EVENT_MILLAGE INT NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (CAR_ID) REFERENCES CARS(ID)
);

